-- MySQL Script generated by MySQL Workbench
-- Tue Jan 30 14:24:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema walk_in_portal_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema walk_in_portal_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `walk_in_portal_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `walk_in_portal_db` ;

-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`job_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`job_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`time_slots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`time_slots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile_image` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `resume` VARCHAR(255) NULL DEFAULT NULL,
  `portfolio` VARCHAR(255) NULL DEFAULT NULL,
  `ref_emp_name` VARCHAR(45) NULL DEFAULT NULL,
  `email_subscription` TINYINT NULL DEFAULT '0',
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`walk_in_additional_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`walk_in_additional_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`pre_reqs_app_process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`pre_reqs_app_process` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `general_instructions` TEXT NULL DEFAULT NULL,
  `exam_instructions` TEXT NULL DEFAULT NULL,
  `min_sys_reqs` TEXT NULL DEFAULT NULL,
  `application_process` TEXT NULL DEFAULT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pre_reqs_app_process_walk_in_applications1`
    FOREIGN KEY (`id`)
    REFERENCES `walk_in_portal_db`.`walk_in_applications` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`walk_in_venues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`walk_in_venues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `line1` VARCHAR(255) NOT NULL,
  `line2` VARCHAR(255) NULL DEFAULT NULL,
  `landmark` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(50) NOT NULL,
  `pincode` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`walk_in_applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`walk_in_applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `expiry_date` DATE NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `additional_info` INT NULL DEFAULT NULL,
  `pre_reqs` INT NULL DEFAULT NULL,
  `venue` INT NULL DEFAULT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_walk_in_applications_walk_in_additional_info1_idx` (`additional_info` ASC) VISIBLE,
  INDEX `fk_walk_in_applications_walk_in_venue1_idx` (`venue` ASC) VISIBLE,
  INDEX `fk_walk_in_applications_walk_in_pre_reqs1_idx` (`pre_reqs` ASC) VISIBLE,
  CONSTRAINT `fk_walk_in_applications_walk_in_additional_info1`
    FOREIGN KEY (`additional_info`)
    REFERENCES `walk_in_portal_db`.`walk_in_additional_info` (`id`),
  CONSTRAINT `fk_walk_in_applications_walk_in_pre_reqs1`
    FOREIGN KEY (`pre_reqs`)
    REFERENCES `walk_in_portal_db`.`pre_reqs_app_process` (`id`),
  CONSTRAINT `fk_walk_in_applications_walk_in_venue1`
    FOREIGN KEY (`venue`)
    REFERENCES `walk_in_portal_db`.`walk_in_venues` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`user_applied_applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`user_applied_applications` (
  `user_id` INT NOT NULL,
  `walk_in_application_id` INT NOT NULL,
  `time_slot_id` INT NOT NULL,
  `resume` VARCHAR(250) NULL DEFAULT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `walk_in_application_id`),
  INDEX `fk_users_has_walk_in_applications_walk_in_applications1_idx` (`walk_in_application_id` ASC) VISIBLE,
  INDEX `fk_users_has_walk_in_applications_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_applied_applications_time_slots1_idx` (`time_slot_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_applied_applications_time_slots1`
    FOREIGN KEY (`time_slot_id`)
    REFERENCES `walk_in_portal_db`.`time_slots` (`id`),
  CONSTRAINT `fk_users_has_walk_in_applications_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `walk_in_portal_db`.`users` (`id`),
  CONSTRAINT `fk_users_has_walk_in_applications_walk_in_applications1`
    FOREIGN KEY (`walk_in_application_id`)
    REFERENCES `walk_in_portal_db`.`walk_in_applications` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`application_preference_job_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`application_preference_job_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `application_id` INT NOT NULL,
  `job_role_id` INT NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_applied_applications_has_job_roles_job_roles1_idx` (`job_role_id` ASC) VISIBLE,
  INDEX `fk_users_applied_applications_has_job_roles_users_applied_a_idx` (`user_id` ASC, `application_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_applied_applications_has_job_roles_job_roles1`
    FOREIGN KEY (`job_role_id`)
    REFERENCES `walk_in_portal_db`.`job_roles` (`id`),
  CONSTRAINT `fk_users_applied_applications_has_job_roles_users_applied_app1`
    FOREIGN KEY (`user_id` , `application_id`)
    REFERENCES `walk_in_portal_db`.`user_applied_applications` (`user_id` , `walk_in_application_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`colleges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`colleges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`qualifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`qualifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`streams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`streams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`education_qualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`education_qualification` (
  `user_id` INT NOT NULL,
  `qualification_id` INT NOT NULL,
  `stream_id` INT NOT NULL,
  `college_id` INT NOT NULL,
  `year_of_passing` DECIMAL(4,0) NOT NULL,
  `aggregate_percentage` DECIMAL(2,0) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  INDEX `fk_education_qualification_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_education_qualification_qualifications1_idx` (`qualification_id` ASC) VISIBLE,
  INDEX `fk_education_qualification_streams1_idx` (`stream_id` ASC) VISIBLE,
  INDEX `fk_education_qualification_colleges1_idx` (`college_id` ASC) VISIBLE,
  CONSTRAINT `fk_education_qualification_colleges1`
    FOREIGN KEY (`college_id`)
    REFERENCES `walk_in_portal_db`.`colleges` (`id`),
  CONSTRAINT `fk_education_qualification_qualifications1`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `walk_in_portal_db`.`qualifications` (`id`),
  CONSTRAINT `fk_education_qualification_streams1`
    FOREIGN KEY (`stream_id`)
    REFERENCES `walk_in_portal_db`.`streams` (`id`),
  CONSTRAINT `fk_education_qualification_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `walk_in_portal_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`enum_applicant_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`enum_applicant_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`enum_technology_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`enum_technology_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`enum_technology_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`enum_technology_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`main_technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`main_technologies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`other_technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`other_technologies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`professional_qualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`professional_qualification` (
  `user_id` INT NOT NULL,
  `applicant_type` INT NOT NULL,
  `applied_earlier` VARCHAR(45) NULL DEFAULT NULL,
  `years_of_experience` INT NULL DEFAULT NULL,
  `current_ctc` INT NULL DEFAULT NULL,
  `expected_ctc` INT NULL DEFAULT NULL,
  `notice_period_end_date` DATE NULL DEFAULT NULL,
  `notice_period_duration` INT NULL DEFAULT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  INDEX `fk_professional_qualification_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_professional_qualification_enum_applicant_type1_idx` (`applicant_type` ASC) VISIBLE,
  CONSTRAINT `fk_professional_qualification_enum_applicant_type1`
    FOREIGN KEY (`applicant_type`)
    REFERENCES `walk_in_portal_db`.`enum_applicant_type` (`id`),
  CONSTRAINT `fk_professional_qualification_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `walk_in_portal_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`user_preferes_job_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`user_preferes_job_roles` (
  `user_id` INT NOT NULL,
  `job_role_id` INT NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `job_role_id`),
  INDEX `fk_users_has_job_roles_job_roles1_idx` (`job_role_id` ASC) VISIBLE,
  INDEX `fk_users_has_job_roles_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_job_roles_job_roles1`
    FOREIGN KEY (`job_role_id`)
    REFERENCES `walk_in_portal_db`.`job_roles` (`id`),
  CONSTRAINT `fk_users_has_job_roles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `walk_in_portal_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`user_technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`user_technologies` (
  `user_id` INT NOT NULL,
  `technology_id` INT NOT NULL,
  `technology_type` INT NOT NULL,
  `technology_category` INT NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `technology_id`, `technology_type`, `technology_category`),
  INDEX `fk_users_has_technologies_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_technologies_enum_technology_type1_idx` (`technology_type` ASC) VISIBLE,
  INDEX `fk_users_technologies_enum_technology_category1_idx` (`technology_category` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_technologies_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `walk_in_portal_db`.`users` (`id`),
  CONSTRAINT `fk_users_technologies_enum_technology_category1`
    FOREIGN KEY (`technology_category`)
    REFERENCES `walk_in_portal_db`.`enum_technology_category` (`id`),
  CONSTRAINT `fk_users_technologies_enum_technology_type1`
    FOREIGN KEY (`technology_type`)
    REFERENCES `walk_in_portal_db`.`enum_technology_type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`walk_in_applications_has_job_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`walk_in_applications_has_job_roles` (
  `walk_in_application_id` INT NOT NULL,
  `job_role_id` INT NOT NULL,
  `gross_compensation_package` INT NOT NULL,
  `role_description` TEXT NOT NULL,
  `role_requirements` TEXT NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`walk_in_application_id`, `job_role_id`),
  INDEX `fk_walk_in_applications_has_job_roles_job_roles1_idx` (`job_role_id` ASC) VISIBLE,
  INDEX `fk_walk_in_applications_has_job_roles_walk_in_applications1_idx` (`walk_in_application_id` ASC) VISIBLE,
  CONSTRAINT `fk_walk_in_applications_has_job_roles_job_roles1`
    FOREIGN KEY (`job_role_id`)
    REFERENCES `walk_in_portal_db`.`job_roles` (`id`),
  CONSTRAINT `fk_walk_in_applications_has_job_roles_walk_in_applications1`
    FOREIGN KEY (`walk_in_application_id`)
    REFERENCES `walk_in_portal_db`.`walk_in_applications` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `walk_in_portal_db`.`walk_in_applications_has_time_slots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walk_in_portal_db`.`walk_in_applications_has_time_slots` (
  `walk_in_application_id` INT NOT NULL,
  `time_slot_id` INT NOT NULL,
  `dt_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`walk_in_application_id`, `time_slot_id`),
  INDEX `fk_walk_in_applications_has_time_slots_time_slots1_idx` (`time_slot_id` ASC) VISIBLE,
  INDEX `fk_walk_in_applications_has_time_slots_walk_in_applications_idx` (`walk_in_application_id` ASC) VISIBLE,
  CONSTRAINT `fk_walk_in_applications_has_time_slots_time_slots1`
    FOREIGN KEY (`time_slot_id`)
    REFERENCES `walk_in_portal_db`.`time_slots` (`id`),
  CONSTRAINT `fk_walk_in_applications_has_time_slots_walk_in_applications1`
    FOREIGN KEY (`walk_in_application_id`)
    REFERENCES `walk_in_portal_db`.`walk_in_applications` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
